'use strict';

/**
 * Represents a URL entity
 */
class Url {
  /**
   * @param {Object} data
   */
  constructor(data) {
    /**
     * Point at which the url starts
     * @type {number}
     */
    this.start = data.start;

    /**
     * Point at which the url ends
     * @type {number}
     */
    this.end = data.end;

    /**
     * The link generated by Twitter's URL shortener
     * @type {string}
     */
    this.shortLink = data.url;

    /**
     * The orignal url posted by the user
     * @type {string}
     */
    this.originalLink = data.expanded_url;

    /**
     * Shows how the URL looks on twitter
     * @type {string}
     */
    this.displayedAs = data.display_url;
  }
}

export default Url;
